### ISSUE TITLE
Keycloak mobile

### ISSUE THREAD

**Issue by quochuy6295** [gibahjoe/keycloak_flutter#13]
Are you have run keycloak in mobile, I want to open and access keycloak in mobile app. Can you help some idea if you have done over it! Thanks

**Comment by luis901101** [comment]
You can use any of this plugins:
- [flutter_appauth](https://pub.dev/packages/flutter_appauth)
- [oauth_webauth](https://pub.dev/packages/oauth_webauth)
And there are others, but that are the most useful ones I have used.
