### ISSUE TITLE
TypeError: dart.global.Keykloak is not a constructor

### ISSUE THREAD

**Issue by hamiltonvalerio** [gibahjoe/keycloak_flutter#14]
Hello everyone,

I'm following an exemple on this page (https://pub.dev/packages/keycloak_flutter/example), but when i go to run 'flutter run" in the browser it shows me an error message:  TypeError: dart.global.Keykloak is not a constructor. 
![fluttererror](https://user-images.githubusercontent.com/5330539/173062254-9ce6cc9d-9615-48ed-9a49-dc8f607db979.PNG)

Any idea!?

Thanks!!

**Comment by Zukka** [comment]
In **main.dart** change 

[https://gist.github.com/Zukka/5d05f117b29e67d2d1370210863256a4](url)
![Screenshot 2022-08-02 at 12 08 40](https://user-images.githubusercontent.com/6852409/182349989-9fe296c6-96f3-4abc-b9e8-e3d337d6433e.png)

to

[https://gist.github.com/Zukka/f1c2095b0b2eeedc00d65ed17025589a](url)
![Screenshot 2022-08-02 at 12 10 42](https://user-images.githubusercontent.com/6852409/182350349-8bb0d90f-2e38-45f9-b98c-bfae35fc78ea.png)

**Comment by gibahjoe** [comment]
HI, this issue has been resoled in the latest release. Don't hesitate to reopen if otherwise

**Comment by ymerdrengene** [comment]
It seems this error still occurs. I have tried to use the example and it gives me this error
`TypeError: dart.global.Keycloak is not a constructor`

**Comment by isabellefo** [comment]
I was facing this problem and the solution was to add the keycloak.js file
https://github.com/gibahjoe/keycloak_flutter/blob/master/example/web/js/keycloak.js
