### ISSUE TITLE
This library is not compatible with --release mode

### ISSUE THREAD

**Issue by TMSantos** [gibahjoe/keycloak_flutter#17]
it throws this error at initialization:

![Screenshot 2022-09-06 at 12 53 48](https://user-images.githubusercontent.com/5798822/188628391-71dc311d-f81f-47d7-9ca1-217609ce6ef9.png)

--debug works
--profile doesn't work
--release doesn't work

I guess is because keycloak.js gets obfuscated, changing it's method names

Any ideias?

**Comment by jonl-percsolutions-com** [comment]
I was running into this issue as well.  Cloned the repo and discovered that KeycloakPromise extends Future, which is causing the issue because the JS promise is not a future, which causes this exception to happen when the future chaining checks if the returned value is a future.

**Comment by gibahjoe** [comment]
This has seen been resolved. Closing. Please create another issue if thats not the case.
