### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by sumit-dhiman-solace** [gibahjoe/keycloak_flutter#23]
### Description of the bug

I just copied the code and tried to run into the iOS simulator, but it is not running. 

### Steps to reproduce

I just copied the code and tried to run into the iOS simulator, but it is not running. 

### Expected behavior

I just copied the code and tried to run into the iOS simulator, but it is not running. 

### Platform

iOS

### Browser

Chrome

### Keycloak web version

0.0.20

### Keycloak flutter version

0.0.20

### Flutter version

3.3

### Flutter channel

stable

**Comment by gibahjoe** [comment]
HI. This is for web only. iOS support has not been added yet
