### ISSUE TITLE
Just add import to new project and hav now lot of errors

### ISSUE THREAD

**Issue by JuriSalesski** [gibahjoe/keycloak_flutter#3]
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/configure_web.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/configure_web.dart:4:8: Error: Error when reading '../../flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart': Das System kann den angegebenen Pfad nicht finden.

import 'package:flutter_web_plugins/src/navigation/url_strategy.dart';
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.2/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.2/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
export 'dart:js_util';
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/web_url_strategy.dart:3:30: Error: Type 'PathUrlStrategy' not found.
class WebUrlStrategy extends PathUrlStrategy {
                             ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/web_url_strategy.dart:8:9: Error: Type 'PlatformLocation' not found.
  final PlatformLocation _platformLocation;
        ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:33:20: Error: The method 'promiseToFuture' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'promiseToFuture'.
    authed = await promiseToFuture<bool>(_keycloak.init(initOptions));
                   ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:41:31: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthSuccess = allowInterop(() {
                              ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:44:29: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthError = allowInterop((error) {
                            ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:48:25: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onReady = allowInterop((authenticated) {
                        ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:52:36: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthRefreshError = allowInterop(() {
                                   ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:56:30: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthLogout = allowInterop(() {
                             ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:59:32: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onTokenExpired = allowInterop(() {
                               ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:96:15: Error: The method 'promiseToFuture' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'promiseToFuture'.
        await promiseToFuture(this._keycloak.loadUserProfile());
              ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart:140:12: Error: The method 'promiseToFuture' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'promiseToFuture'.
    return promiseToFuture<bool>(this._keycloak.updateToken(minValidity));
           ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/web_url_strategy.dart:5:36: Error: Method not found: 'BrowserPlatformLocation'.
    this._platformLocation = const BrowserPlatformLocation(),
                                   ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/web_url_strategy.dart:6:13: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  ]) : super(_platformLocation);
            ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/web_url_strategy.dart:8:9: Error: 'PlatformLocation' isn't a type.
  final PlatformLocation _platformLocation;
        ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/web_url_strategy.dart:12:19: Error: Superclass has no method named 'getPath'.
    var p = super.getPath() + _platformLocation.hash;
                  ^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.2-pre/lib/src/configure_web.dart:8:3: Error: Method not found: 'setUrlStrategy'.
  setUrlStrategy(WebUrlStrategy());
  ^^^^^^^^^^^^^^
../../flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:5: Error: Method not found: 'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatformMessage);
    ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by gibahjoe** [comment]
Hi, will take a look at this and push out an update soon.

**Comment by gibahjoe** [comment]
What flutter version are you using?

**Comment by jueser** [comment]
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (3 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by gibahjoe** [comment]
Hi, this package is for flutter web and only works on the beta branch since flutter web is still in beta.
