### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by Achudh** [gibahjoe/keycloak_flutter#8]
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^

../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
export 'dart:js_util';
^

../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:29:20: Error: The method 'promiseToFuture' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'promiseToFuture'.
    authed = await promiseToFuture<bool>(_keycloak.init(initOptions));
                   ^^^^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:37:31: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    _keycloak.onAuthSuccess = allowInterop(() {
                              ^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:40:29: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthError = allowInterop((error) {
                            ^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:44:25: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onReady = allowInterop((authenticated) {
                        ^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:48:36: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthRefreshError = allowInterop(() {
                                   ^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:52:30: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    _keycloak.onAuthLogout = allowInterop(() {

                             ^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:55:32: Error: The method 'allowInterop' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    _keycloak.onTokenExpired = allowInterop(() {
                               ^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:91:15: Error: The method 'promiseToFuture' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'promiseToFuture'.
        await promiseToFuture(this._keycloak.loadUserProfile());
              ^^^^^^^^^^^^^^^
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart:135:12: Error: The method 'promiseToFuture' isn't defined for the class 'KeycloakService'.
 - 'KeycloakService' is from 'package:keycloak_flutter/src/keycloak_service.dart' ('../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/keycloak_flutter-0.0.3/lib/src/keycloak_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'promiseToFuture'.
    return promiseToFuture<bool>(this._keycloak.updateToken(minValidity));
           ^^^^^^^^^^^^^^^

**Comment by gibahjoe** [comment]
This library is for web only. Flutter won't run javascript on the mobile

**Comment by Achudh** [comment]
> This library is for web only. Flutter won't run javascript on the mobile

Yeah, recently saw that ! Thank you so much
