### ISSUE TITLE
Does not Redirect to application  if the browser tab closed without logging out.

### ISSUE THREAD

**Issue by ptawde95** [gibahjoe/keycloak_flutter#9]
**Describe the bug :**

Using the package,i am able to load keycloak login screen and successful redirect back to my application,
but I am not able to load my application page again in the browser if i closed the browser tab without using the logging out from the application. causes below error in the console.
Refused to frame 'MykeycloakURL' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
Also no errors are logged related to keyclaok initialization from the package.

**Example :** localhost:9000/#/ is my URL for homepage which loads successfully after keycloak authenctication, then i closed the page without logout and  copy the URL in new tab page does not load.

**Expected behavior :**
If the User is already login it should display the homepage else redirect to keycloak login

**Flutter Version:**
Flutter 2.0.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (10 weeks ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by gibahjoe** [comment]
Hi, Can you please provide a minimal codebase so that I can recreate the issue you are experiencing. Thanks

**Comment by ptawde95** [comment]
Hi
Thanks for the Response. 
Issue is resolved there was need to add the sso-silent.html url in the Keyclaok callbacks URLs.
